### ISSUE TITLE
short-name-mode="enforcing", unqualified-search-registries 

### ISSUE THREAD

**Issue by westurner** [manics/repo2podman#53]
If the repo2docker Dockerfile template is changed, changing `/etc/containers/registries.conf` shouldn't be necessary for repo2docker/repo2podman, at least:

```bash
FROM buildpack-deps:bionic             # short-name
FROM docker.io/buildpack-deps:bionic   # "qulified" name
```

**Comment by manics** [comment]
Done in https://github.com/jupyterhub/repo2docker/pull/909
