### ISSUE TITLE
Support for podman-remote

### ISSUE THREAD

**Issue by westurner** [manics/repo2podman#66]
STORY: Users can specify a different engine and arguments to the engine in order to use {`podman-remote`, `nerdctl`,} instead of `podman`.

- `podman-remote`
  - 
  - docs: https://docs.podman.io/en/latest/markdown/podman-remote.1.html
  - docs: https://github.com/containers/podman/blob/main/docs/tutorials/remote_client.md
  - vscode flatpak & *podman-remote*: https://github.com/flathub/com.visualstudio.code.tool.podman/blob/master/com.visualstudio.code.tool.podman.yml
  - https://www.google.com/search?q=podman+remote
- `nerdctl`
  -
  - src: https://github.com/containerd/nerdctl
- `podman`
  - 
  - docs: https://docs.podman.io/en/latest/Commands.html
  - docs: https://man.archlinux.org/man/podman.1.en#COMMANDS
  - docs: https://podman.io/docs
  - src: https://github.com/containers/podman

**Comment by westurner** [comment]
- `podman` is hardcoded in the `exec_podman` and `exec_podman_stream` functions:
  - https://github.com/manics/repo2podman/blob/85076c3dd39576686890b8e5b2900795db332273/repo2podman/podman.py#L180
  - https://github.com/manics/repo2podman/blob/85076c3dd39576686890b8e5b2900795db332273/repo2podman/podman.py#L205

**Comment by manics** [comment]
Is `podman-remote` a drop-in replacement for `podman`, so it just requires making the executable configurable? If so that would be a nice way to support other podman compatible CLIs e.g. https://github.com/containerd/nerdctl

**Comment by westurner** [comment]
Thanks!

**Comment by manics** [comment]
Thanks for the idea! Now released as 0.2.0
